language: python
python:
        - "3.5"

before_install:
        - sudo apt-get --quiet=2 update
        - sudo apt-get --quiet=2 install --yes graphviz

install:
        - pip3 install tox

script: tox -r
